import fs from 'node:fs/promises';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire('C:/Users/29707/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');
const { chromium } = require('playwright');
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
await fs.mkdir('test-results', { recursive: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const base = 'http://localhost:5173';
await page.goto(base); await page.getByRole('heading', { name: '今天，想去哪里？' }).waitFor();
await page.screenshot({ path: 'test-results/home-desktop.png', fullPage: true });
const report = [];
for (const width of [390, 360]) {
  await page.setViewportSize({ width, height: 844 });
  for (const route of ['/', '/prepare/pet', '/history', '/binding', '/therapist/login', '/train/pet', '/prepare/missing', '/result/missing']) {
    await page.goto(base + route); await page.waitForTimeout(220);
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
    assert.equal(overflow, false, `${width}px overflow on ${route}`);
    report.push(`${width}px ${route}: no overflow`);
  }
  await page.goto(base); await page.screenshot({ path: `test-results/home-${width}.png`, fullPage: true });
}
await page.setViewportSize({ width: 390, height: 844 });
await page.goto(base);
await page.getByRole('button', { name: '开始体验萌宠互动' }).click();
await page.waitForTimeout(1400);
await page.screenshot({ path: 'test-results/ripple-loading.png' });
assert.equal(await page.locator('.launch-overlay').count(), 1);
const rippleState = await page.locator('.rain-ripple').evaluateAll(nodes => nodes.map(n => ({ opacity: +getComputedStyle(n).opacity, transform: getComputedStyle(n).transform })));
assert.ok(rippleState.some(r => r.opacity > .02));
assert.ok(new Set(rippleState.map(r => r.transform)).size > 3);
await page.waitForURL('**/prepare/pet');
await page.getByRole('button', { name: '了解了，继续' }).click();
await page.getByRole('button', { name: '左手', exact: true }).click();
assert.equal(await page.getByRole('button', { name: '左手', exact: true }).getAttribute('aria-pressed'), 'true');
await page.screenshot({ path: 'test-results/hand-select-390.png', fullPage: true });
await page.goto(base + '/binding');
await page.getByLabel('怎么称呼你').fill('小禾');
await page.getByLabel('治疗师邀请码').fill('HELLO');
await page.getByRole('button', { name: '查找治疗师' }).click();
await page.getByText('绑定服务暂未开放，你仍可以训练并保留本机记录。').waitFor();
await page.goto(base + '/design');
await page.getByRole('button', { name: '开始训练', exact: true }).click();
await page.waitForTimeout(3300);
await page.getByRole('button', { name: '暂停训练' }).click();
await page.getByRole('heading', { name: '把节奏，留在这里' }).waitFor();
await page.getByRole('button', { name: '继续训练' }).click();
await page.waitForTimeout(3250);
await page.getByRole('button', { name: '手部丢失', exact: true }).click();
await page.getByRole('heading', { name: '没看到手', exact: true }).waitFor();
await page.getByRole('button', { name: '找回手部 · 倒数' }).click();
await page.waitForTimeout(3250);
await page.getByRole('button', { name: 'Perfect', exact: true }).click();
await page.locator('.grade-perfect').waitFor();
await page.locator('.design-phone').screenshot({ path: 'test-results/training-390.png' });
await page.getByRole('button', { name: '查看训练完成' }).click();
await page.getByRole('heading', { name: '完成今天的训练' }).waitFor();
await page.screenshot({ path: 'test-results/result-390.png', fullPage: true });
await page.goto(base + '/history');
await page.getByRole('heading', { name: '第一段节奏，等你开启' }).waitFor();
report.push('Design simulation never creates real history; pause, recovery, result and binding error checked.');
await page.emulateMedia({ reducedMotion: 'reduce' });
await page.goto(base + '/design');
await page.getByRole('button', { name: '加载', exact: true }).click();
await page.waitForTimeout(1200);
const scales = await page.locator('.rain-ripple').evaluateAll(nodes => nodes.map(n => getComputedStyle(n).transform));
assert.ok(scales.every(s => s.startsWith('matrix(0.8, 0, 0, 0.8')));
report.push('Reduced motion: ripple positions and scales remain still.');
assert.deepEqual(errors, [], 'Unexpected browser errors');
await fs.writeFile('test-results/browser-report.txt', report.join('\n'));
console.log(report.join('\n'));
await browser.close();
